reference: "reference/genome.fa" # Replace with your actual reference
samplesheet: "samples.csv" # Replace with your actual Samplesheet
outdir: "./results"
umi_len: 12  # Remove or null to skip UMI extraction
umi_regex: "ATCGTCGGA" # only include if using UMIs 
merged: false  # true to use bbmerge
